# Generated by Django 5.1.6 on 2025-07-15 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_check_in_alter_booking_check_out'),
        ('kot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kot',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
