"""
Django settings for resortsathi project.
Generated by 'django-admin startproject' using Django 5.1.6.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# === Base Paths ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Environment ===
ENVIRONMENT = os.getenv("DJANGO_ENV", "development")

# === Security ===
SECRET_KEY = os.getenv("SECRET_KEY", "insecure-dev-key")
DEBUG = ENVIRONMENT == "development"
ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = ["*"]

# === Installed Applications ===
INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'nepali_datetime_field',

    # Custom apps
    'accounts',
    'api',
    'crm',
    'kot',
    'saas',
    'loan',
    'rooms',
    'reviews',
    'resorts',
    'support',
    'tickets',
    'bookings',
    'payments',
    'dashboard',
    'inventory',
    'accounting',
    'hr',
]

# === Middleware ===
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# === URLs & WSGI ===
ROOT_URLCONF = 'resortsathi.urls'
WSGI_APPLICATION = 'resortsathi.wsgi.application'

# === Templates ===
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# === Custom User Model ===
AUTH_USER_MODEL = 'accounts.User'

# === Admin Branding ===
ADMIN_SITE_HEADER = "ResortSathi Admin"
ADMIN_SITE_TITLE = "ResortSathi Dashboard"

# === Database ===
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME_DEV'),
            'USER': os.getenv('DB_USER_DEV'),
            'PASSWORD': os.getenv('DB_PASSWORD_DEV'),
            'HOST': os.getenv('DB_HOST_DEV'),
            'PORT': os.getenv('DB_PORT_DEV', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST', 'db'),
            'PORT': os.getenv('DB_PORT', '5432'),
            # 'OPTIONS': {
            #     'sslmode': 'require',
            # }
        }
    }

# === Password Validation ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === Localization ===
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kathmandu'
USE_I18N = True
USE_TZ = True

# === Static & Media Files ===
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# === Auto Field ===
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
