# Generated by Django 5.1.6 on 2025-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('corporate', 'Corporate'), ('ordinary', 'Ordinary'), ('organization', 'Organization')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_address', models.TextField()),
                ('registration_number', models.CharField(max_length=100)),
                ('pan_or_vat_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('spokesperson_name', models.CharField(max_length=255)),
                ('spokesperson_email', models.EmailField(max_length=254)),
                ('spokesperson_phone', models.CharField(max_length=20)),
                ('spokesperson_id_image', models.ImageField(blank=True, null=True, upload_to='corporate_ids/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdinaryCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('corporate', 'Corporate'), ('ordinary', 'Ordinary'), ('organization', 'Organization')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('nationality', models.CharField(max_length=100)),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='ordinary_ids/')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('corporate', 'Corporate'), ('ordinary', 'Ordinary'), ('organization', 'Organization')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_type', models.CharField(choices=[('ngo', 'Non-Governmental Organization'), ('npo', 'Non-Profit Organization'), ('charity', 'Charity'), ('social_enterprise', 'Social Enterprise')], default='npo', max_length=50)),
                ('organization_address', models.TextField()),
                ('registration_number', models.CharField(help_text='Issued by Social Welfare Council or other body', max_length=100)),
                ('pan_or_tax_exemption_number', models.CharField(blank=True, max_length=100, null=True)),
                ('official_email', models.EmailField(max_length=254)),
                ('official_contact_number', models.CharField(max_length=20)),
                ('representative_name', models.CharField(max_length=255)),
                ('representative_email', models.EmailField(max_length=254)),
                ('representative_phone', models.CharField(max_length=20)),
                ('representative_id_image', models.ImageField(blank=True, null=True, upload_to='organization_ids/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='CustomerType',
        ),
    ]
