# Generated by Django 5.1.6 on 2025-07-01 11:16

import nepali_datetime_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=nepali_datetime_field.models.NepaliDateField(),
        ),
    ]
