# Generated by Django 5.1.6 on 2025-07-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-issued_at']},
        ),
    ]
